### ISSUE TITLE
On load, scale object to 1:1:1 unit size

### ISSUE THREAD

**Issue by msurguy** [osresearch/hiddenwire#16]
When STL is loaded, it would be helpful to always have the same initial size for any STL. 
For example, `ln` does this with a unit cube and fits the object inside the unit cube: https://github.com/fogleman/ln/blob/master/ln/mesh.go , https://github.com/fogleman/ln/blob/12e6c6e7445909f817f1b8d5581be4255ffa1437/examples/slicer.go#L18

This way, no matter what STL you load, your zoom level and camera position can remain the same.

**Comment by osresearch** [comment]
That would also make the eye separation adjustment easier since it gets weird for really large objects.

**Comment by osresearch** [comment]
I've added code to do this. https://github.com/osresearch/plotter-vision/commit/bc72ec1a7ab577d9abd4c8a61bb9adf52420dea3

We'll see how well it works in practice.

**Comment by msurguy** [comment]
Thank you, @osresearch !
