### ISSUE TITLE
Provide a view port for exported SVG

### ISSUE THREAD

**Issue by pilhuhn** [osresearch/hiddenwire#19]
Currently the exported SVG has a width/weight, that is fixed and much larger than the actual drawn surface.
It would be good to have a view-port that shows the part of the canvas that is really used.

For example the bunny in https://twitter.com/pilhuhn/status/1345759428239364098
has `<svg width='1480px' height='885px' ...>`
but the actual path data is:
```
minX  : 351, maxX = 1051
minY  : 11, maxY = 760

```
which translates to Height: 700.0, Width : 749.0

**Comment by osresearch** [comment]
Does #26 satisfy this? It now clips the segments to the viewport.

**Comment by osresearch** [comment]
Hopefully this is working for you.  It seems to fine for me.
