### ISSUE TITLE
place colours on seperate layers

### ISSUE THREAD

**Issue by ithinkido** [osresearch/hiddenwire#22]
One idea , how about placing the red/blue colours on two seperate layers. If you are going to plot them, this is going to have to be done one way or the other.

**Comment by osresearch** [comment]
SVG doesn't have its own concept of layers, although Inkscape implements them with special groups.  I've added code to create these groups when creating the download file.

**Comment by osresearch** [comment]
![image](https://user-images.githubusercontent.com/3068843/143263390-be2e017d-a887-42ca-8a8f-9b7ddf3fd23e.png)

Hopefully this works in other tools, too.

**Comment by ithinkido** [comment]
Thanks for implementing this.
